site_name: 'NabBot'
site_description: 'A discord bot for the MMO Tibia'
site_author: 'Allan Galarza'
site_url: 'https://galarzaa90.github.io/NabBot/'

site_name: NabBot
theme:
  name: material
  palette:
    primary: 'deep purple'
    accent: 'orange'
  logo: 'assets/images/icon.png'
  favicon: 'assets/images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite

extra:
  social:
    - type: 'github'
      link: 'https://github.com/galarzaa90'

repo_url: https://github.com/Galarzaa90/NabBot
edit_uri: ""
pages:
    - Home: index.md
    - Install Guide: install.md
    - Permissions: permissions.md
    - FAQ: faq.md